using System.Net.Http.Headers;
using System.Text;
using Microsoft.Extensions.Logging;
using MyPrivateServer.Core;

namespace MyPrivateServer.WebHosting;

public sealed record CaddyStatus(bool Installed, bool Running, string? Version, string? Problem);

/// <summary>
/// Renders a Caddyfile from the site list and applies it through Caddy's local admin API (hot reload,
/// no dropped connections). Caddy is started as a child process if it is not already running.
/// </summary>
public sealed class CaddyManager(ServerPaths paths, IProcessRunner runner, IHttpClientFactory http, ILogger<CaddyManager> log) : IDisposable
{
    public const string AdminAddress = "127.0.0.1:2019";
    readonly ManagedProcess _proc = new("caddy");
    string ConfigFile => Path.Combine(paths.ConfigDirectory, "Caddyfile");

    public static string Render(IEnumerable<Site> sites, Func<Site, string?> rootFor)
    {
        static string Quote(string path)
        {
            var p = path.Replace('\\', '/');
            if (p.IndexOfAny(['"', '\n', '\r', '{', '}']) >= 0) throw new UserFacingException("Unsafe characters in a website path.");
            return "\"" + p + "\"";
        }
        var sb = new StringBuilder();
        sb.AppendLine("# Generated by My Private Server. Changes are overwritten.");
        sb.AppendLine("{");
        sb.AppendLine($"\tadmin {AdminAddress}");
        sb.AppendLine("}");
        foreach (var s in sites.Where(s => s.Enabled).OrderBy(s => s.Port))
        {
            var addresses = new List<string> { $"http://:{s.Port}" };
            addresses.AddRange(s.Hostnames);
            sb.AppendLine();
            sb.AppendLine($"# {s.Name} ({s.Kind})");
            sb.AppendLine(string.Join(", ", addresses) + " {");
            sb.AppendLine("\tencode zstd gzip");
            sb.AppendLine("\theader {");
            sb.AppendLine("\t\tX-Content-Type-Options nosniff");
            sb.AppendLine("\t\tReferrer-Policy strict-origin-when-cross-origin");
            sb.AppendLine("\t\t-Server");
            sb.AppendLine("\t}");
            switch (s.Kind)
            {
                case SiteKind.Static:
                    var root = rootFor(s);
                    if (root is null) { sb.AppendLine("\trespond \"Not deployed yet\" 503"); break; }
                    sb.AppendLine($"\troot * {Quote(root)}");
                    if (s.SpaFallback) sb.AppendLine("\ttry_files {path} {path}/ /index.html");
                    sb.AppendLine("\tfile_server");
                    break;
                case SiteKind.Php:
                    var phpRoot = rootFor(s);
                    if (phpRoot is null) { sb.AppendLine("\trespond \"Not deployed yet\" 503"); break; }
                    sb.AppendLine($"\troot * {Quote(phpRoot)}");
                    sb.AppendLine($"\tphp_fastcgi 127.0.0.1:{(s.UpstreamPort > 0 ? s.UpstreamPort : 9000)}");
                    sb.AppendLine("\tfile_server");
                    break;
                default:
                    sb.AppendLine($"\treverse_proxy 127.0.0.1:{s.UpstreamPort}");
                    break;
            }
            sb.AppendLine("}");
        }
        return sb.ToString();
    }

    public async Task ApplyAsync(IReadOnlyList<Site> sites, Func<Site, string?> rootFor, CancellationToken ct)
    {
        var text = Render(sites, rootFor);
        await File.WriteAllTextAsync(ConfigFile, text, ct);
        var exe = runner.Find("caddy");
        if (exe is null) { log.LogWarning("Caddy is not installed; website configuration saved but not served."); return; }
        if (await ReloadAsync(text, ct)) return;
        _proc.Start(exe, ["run", "--config", ConfigFile, "--adapter", "caddyfile"]);
        for (var i = 0; i < 20 && !(await StatusAsync(ct)).Running; i++) await Task.Delay(250, ct);
        if (!(await StatusAsync(ct)).Running)
        {
            var reason = _proc.Log(10).LastOrDefault(l => l.Contains("Error", StringComparison.OrdinalIgnoreCase)) ?? "unknown error";
            throw new UserFacingException("The web server (Caddy) could not start: " + reason, 500);
        }
    }

    async Task<bool> ReloadAsync(string caddyfile, CancellationToken ct)
    {
        try
        {
            var client = http.CreateClient("caddy");
            using var content = new StringContent(caddyfile, Encoding.UTF8);
            content.Headers.ContentType = new MediaTypeHeaderValue("text/caddyfile");
            using var resp = await client.PostAsync($"http://{AdminAddress}/load", content, ct);
            if (resp.IsSuccessStatusCode) return true;
            throw new UserFacingException("Web server rejected the configuration: " + await resp.Content.ReadAsStringAsync(ct), 500);
        }
        catch (HttpRequestException) { return false; }
    }

    public async Task<CaddyStatus> StatusAsync(CancellationToken ct)
    {
        var exe = runner.Find("caddy");
        if (exe is null) return new(false, false, null, "Caddy is not installed. The production installer bundles it; for now place caddy.exe in the tools folder.");
        try
        {
            var client = http.CreateClient("caddy");
            using var resp = await client.GetAsync($"http://{AdminAddress}/config/", ct);
            return new(true, resp.IsSuccessStatusCode, null, null);
        }
        catch (HttpRequestException) { return new(true, false, null, "Caddy is not running."); }
    }

    public IReadOnlyList<string> Logs() => _proc.Log(200);
    public void Dispose() => _proc.Dispose();
}
